<?php

/**
 * @file
 * Defines management/helper/display functions for page like content.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\NestedArray;

// @codingStandardsIgnoreLine
define('ISLANDORA_PAGED_CONTENT_EDIT_OCR', 'Edit existing OCR stream');

/**
 * Implements hook_theme().
 */
function islandora_paged_content_theme() {
  return [
    'islandora_paged_content_page_navigator' => [
      'file' => 'theme/theme.inc',
      'variables' => [
        'object' => NULL,
      ],
    ],
    'swaptable' => [
      'render element' => 'element',
      'file' => 'theme/theme.inc',
    ],
  ];
}

/**
 * Determine whether or not to show this modules manage tab.
 *
 * @return bool
 *   TRUE if they can access, FALSE otherwise.
 */
function islandora_paged_content_manage_page_access_callback($object, array $content_models) {
  $permissions = [
    ISLANDORA_ADD_DS,
    ISLANDORA_METADATA_EDIT,
    ISLANDORA_PURGE,
  ];
  return islandora_user_access_check($object, $permissions, $content_models);
}

/**
 * Checks whether the user can access the "manage pages" page.
 *
 * @return bool
 *   TRUE if they can access, FALSE otherwise.
 */
function islandora_paged_content_manage_pages_access_callback($object, array $content_models) {
  $permissions = [
    ISLANDORA_ADD_DS,
    ISLANDORA_METADATA_EDIT,
    ISLANDORA_PURGE,
    ISLANDORA_INGEST,
  ];
  return islandora_user_access_check($object, $permissions, $content_models);
}

/**
 * Implements hook_permission().
 */
function islandora_paged_content_permission() {
  return [
    ISLANDORA_PAGED_CONTENT_EDIT_OCR => [
      'title' => t('Edit OCR stream'),
      'description' => t('Allows users to edit existing OCR stream. Note: Fedora XACML security policies may override this permission.'),
    ],
  ];
}

/**
 * Callback to process the swaptable form element.
 *
 * Adds a select field that allows the user to select the number of pages to
 * display in each table.
 */
function swaptable_process(array $element, FormStateInterface $form_state) {
  // Fetches the value from the element, supports nested values.
  $get_default_value = function ($name, $default) use ($element) {
    $key_exists = NULL;
    $name = is_array($name) ? $name : [$name];
    $value = NestedArray::getValue($element['#value'], $name, $key_exists);
    return $key_exists ? $value : $default;
  };
  $options = [10, 25, 50, 100];
  $default = isset($element['#value']['display']) ? $element['#value']['display'] : $options[0];
  // Assumes only one swaptable per form/page.
  $element['#prefix'] = '<div id="swaptable-ajax-wrapper">';
  $element['#suffix'] = '</div>';
  $element['display'] = [
    '#type' => 'select',
    '#title' => t('Display'),
    '#options' => array_combine($options, $options),
    '#default_value' => $default,
    '#description' => t('The number of pages to display in each table.'),
    '#ajax' => [
      'callback' => 'swaptable_change_number_of_pages_displayed',
      'wrapper' => 'swaptable-ajax-wrapper',
    ],
  ];
  // The limit for pagers is set by the "Display" select form element.
  $element['#pager']['limit'] = $default;
  // Hidden fields are used to contain the current page number for each table
  // this is used by the javascript to determine the correct index of the
  // rendered elements and by ajax to identify what should be rendered when
  // using the pager.
  $element['page'] = [
    'left' => [
      '#type' => 'hidden',
      '#value' => pager_find_page($element['#pager']['element']['left']),
    ],
    'right' => [
      '#type' => 'hidden',
      '#value' => pager_find_page($element['#pager']['element']['right']),
    ],
  ];
  // Hidden fields are used to store the new order of the table rows, as
  // well as what rows have been directly modified by the user (not including
  // the automatic shifting that occurs).
  $element['order'] = [
    '#type' => 'hidden',
    '#value' => $get_default_value('order', Element::children($element['#rows'])),
  ];
  $element['modified'] = [
    '#type' => 'hidden',
    '#value' => $get_default_value('modified', []),
  ];
  // Hidden button will be used to rebuild the form when a use clicks on a pager
  // link or modifies the ordering of the table.
  $element['load'] = [
    '#type' => 'button',
    '#attributes' => ['style' => 'display:none;'],
    '#executes_submit_callback' => FALSE,
    '#value' => t('load'),
    '#ajax' => [
      'callback' => 'swaptable_change_number_of_pages_displayed',
      'wrapper' => 'swaptable-ajax-wrapper',
      'method' => 'replace',
    ],
  ];
  return $element;
}

/**
 * Ajax callback for changing the number of pages displayed.
 */
function swaptable_change_number_of_pages_displayed(array $form, FormStateInterface $form_state) {
// @codingStandardsIgnoreLine
  $find_swaptable = function ($form) use (&$find_swaptable) {
    if (isset($form['#type']) && $form['#type'] == 'swaptable') {
      return $form;
    }
    foreach (Element::children($form) as $child) {
// @codingStandardsIgnoreLine
      $result = $find_swaptable($form[$child]);
      if ($result !== NULL) {
        return $result;
      }
    }
    return NULL;
  };
  // Assumes only one swaptable per form.
  return $find_swaptable($form);
}

/**
 * Implements hook_islandora_object_ingested().
 */
function islandora_paged_content_islandora_object_ingested(AbstractObject $object) {
  module_load_include('inc', 'islandora_paged_content', 'includes/utilities');
  // Only do this check on paged content that have PDFs.
  $applicable_paged_cmodels = islandora_paged_content_retrieve_applicable_cmodels();
  if (array_intersect(array_keys($applicable_paged_cmodels), $object->models) && isset($object['PDF'])) {
    module_load_include('inc', 'islandora_paged_content', 'includes/db');
    islandora_paged_content_cleanup_source_pdf($object->id);
  }
}

/**
 * Implements hook_islandora_solr_query().
 */
function islandora_paged_content_islandora_solr_query($islandora_solr_query) {
  if (\Drupal::config('islandora_paged_content.settings')->get('islandora_paged_content_hide_pages_solr')) {
    $fq = \Drupal::config('islandora_paged_content.settings')->get('islandora_paged_content_solr_fq');
    if (!empty($fq)) {
      $islandora_solr_query->solrParams['fq'][] = $fq;
    }
  }
}
